# Generated by Django 2.2.28 on 2022-06-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to='orders/invoices'),
        ),
        migrations.AlterField(
            model_name='order',
            name='packing_video',
            field=models.FileField(blank=True, null=True, upload_to='orders/videos'),
        ),
    ]
