# Generated by Django 2.2.27 on 2022-04-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20220416_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='style',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
