# Generated by Django 2.2.27 on 2022-04-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20220417_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='suborder',
            name='style',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
