# Generated by Django 2.2.27 on 2022-04-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_suborder_style'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suborder',
            name='style',
        ),
        migrations.AddField(
            model_name='order',
            name='style',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
