# Generated by Django 2.2.27 on 2022-04-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20220417_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='packinglist',
            name='shipping_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='packinglist',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
