# Generated by Django 2.2.28 on 2022-04-18 09:58

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_packinglist_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=6, max_length=6, prefix='', unique=True),
        ),
    ]
