# Generated by Django 2.2.28 on 2022-04-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_sid'),
    ]

    operations = [
        migrations.AddField(
            model_name='packinglist',
            name='after_tax_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
