# Generated by Django 2.2.28 on 2022-04-18 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_packinglist_after_tax_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packinglist',
            name='after_tax_total',
        ),
        migrations.RemoveField(
            model_name='packinglist',
            name='shipping_cost',
        ),
        migrations.RemoveField(
            model_name='packinglist',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='packinglist',
            name='total',
        ),
    ]
