# Generated by Django 2.2.28 on 2022-04-18 12:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20220418_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='packinglist',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='packinglist',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
