# Generated by Django 2.2.28 on 2022-06-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20220418_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='packinglist',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to='packing-list/invoices'),
        ),
        migrations.AddField(
            model_name='packinglist',
            name='packing_video',
            field=models.FileField(blank=True, null=True, upload_to='packing-list/videos'),
        ),
        migrations.AddField(
            model_name='packinglist',
            name='tracking_number_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
