# Generated by Django 2.2.28 on 2022-06-28 03:49

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=6, max_length=6, prefix='', unique=True),
        ),
    ]
