# Generated by Django 2.2.27 on 2022-04-15 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_half_pack_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
