# Generated by Django 2.2.27 on 2022-04-17 10:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20220416_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='half_pack_order',
        ),
        migrations.AddField(
            model_name='product',
            name='half_pack_styles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=32), blank=True, null=True, size=None),
        ),
    ]
