# Generated by Django 2.2.27 on 2022-04-17 11:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20220417_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='half_pack_orders',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
