# Generated by Django 2.2.27 on 2022-04-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20220417_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='upload_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
